const WINNER_MODE = 'WINNER_MODE'
const LOSER_MODE = 'LOSER_MODE'
const CALL_SIGN = 'CALL_SIGN'

const PLAYER_VS_PLAYER = 'PLAYER_VS_PLAYER'


export {
    WINNER_MODE,
    LOSER_MODE,
    CALL_SIGN,
    PLAYER_VS_PLAYER
}